# Funciones estadísticas

In [ ]:
W=np.arange(1,22,2)
print("Arreglo: ", W)

Arreglo:  [ 1  3  5  7  9 11 13 15 17 19 21]


In [ ]:
print(W.mean())

11.0


In [ ]:
print(W.sum())

121


In [ ]:
print(W.min())

1


In [ ]:
print(W.max())

21


# Funciones universales

In [ ]:
np.square(W)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361, 441])

In [ ]:
np.sqrt(W)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894,
       4.58257569])

In [ ]:
np.exp(W)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08, 1.31881573e+09])

Numpy aplica operaciones aritméticas sobre arreglos que no tienen la misma forma shape), esa propiedad se llama **broadcasting**

In [ ]:
W1=np.arange(5)
W2=np.array([3])
print("Shape W1: ",W1.shape)
print("W1: ",W1)
print()
print("Shape W2: ",W2.shape)
print("W2: ",W2)

Shape W1:  (5,)
W1:  [0 1 2 3 4]

Shape W2:  (1,)
W2:  [3]


In [ ]:
W1 + W2

array([3, 4, 5, 6, 7])